### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by 36Exiaotiangua** [BreezeFreak/Django_demo--#4]
请问有spl文件或是数据集吗

**Comment by djanchew** [comment]
@36Exiaotiangua 你好, 正要写到 migrations 或者 fixtures 文件里, 可以在项目运行之前初始化数据
`python3 manage.py migrate`  
或者  
`python3 manage.py loaddata fixtures/*`  

请留意一下下次更新, 最近会找时间来完成

**Comment by 36Exiaotiangua** [comment]
好的好的

**Comment by djanchew** [comment]
@36Exiaotiangua 已完成
